In [ ]:
# adding data augmentation 

In [86]:
import numpy as np
import copy
import os
import sys
import math
from tqdm import tqdm
from scripts import dataset
from scripts import config

from matplotlib import pyplot as plt
%matplotlib inline

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load data set

In [ ]:
# load dataset
# Let's load dataset
dataset_name = 'met'

if dataset_name not in ['met', 'lsp', 'mpii']:
    raise ValueError('Unknown dataset: {}'.format(dataset_name))

if dataset_name == 'mpii':
    TEST_CV_FILEPATH = os.path.join(config.MPII_DATASET_ROOT, 'test_joints.csv')
    IMG_PATH_PREFIX = os.path.join(config.MPII_DATASET_ROOT, 'images')
    symmetric_joints = "[[12, 13], [11, 14], [10, 15], [2, 3], [1, 4], [0, 5]]"
    ignore_label = -100500
elif dataset_name == 'lsp': # LSP dataset
    TEST_CV_FILEPATH = os.path.join(config.LSP_DATASET_ROOT, 'test_joints.csv')
    IMG_PATH_PREFIX = os.path.join(config.LSP_DATASET_ROOT, 'images')
    symmetric_joints = "[[8, 9], [7, 10], [6, 11], [2, 3], [1, 4], [0, 5]]"
    ignore_label = -1
elif dataset_name == 'met': # MET dataset
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity1.csv') # test only one image
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity.csv')
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity_with_head.csv')
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity_wo.csv')
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity_wo_ub.csv') # cleaned up
    TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity_20180618.csv') # joint rechecked! (2018.06.18) 
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity-met_n10.csv') # joint rechecked! (2018.06.18)    
    # for debugging
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'writing46.csv')  # with valid joints info
    #TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'writing46nv.csv')  # without valid joints info
    
    TEST_CV_FILEPATH = os.path.join(config.MET_DATASET_ROOT, 'activity1.csv')  # without valid joints info

    IMG_PATH_PREFIX = os.path.join(config.MET_DATASET_ROOT)
    symmetric_joints = "[[8, 9], [7, 10], [6, 11], [2, 3], [1, 4], [0, 5]]"
    ignore_label = -1
else:
    pass
 
    
print(TEST_CV_FILEPATH)
print(IMG_PATH_PREFIX)

test_dataset = dataset.PoseDataset(
    TEST_CV_FILEPATH,
    IMG_PATH_PREFIX, 227,
    fliplr=False, rotate=False,
    shift=None,
    #bbox_extension_range=(1.0, 1.0),
    bbox_extension_range=(1.4, 1.4),
    coord_normalize=True,
    gcn=True,
    fname_index=0,
    joint_index=1,
    symmetric_joints=symmetric_joints,
    ignore_label=ignore_label,
    should_return_bbox=True,
    should_downscale_images=True,
    downscale_height=400
)

print("dataset with {} images ready".format(len(test_dataset)))

## data augmentation by horizontal flip

In [ ]:
# read one image 

from tools import augment

imageIdx = 0

image=test_dataset.get_original_image(imageIdx)    
image_id, joints = test_dataset.joints[imageIdx]
is_valid_joints, bbox = test_dataset.info[imageIdx]
print(image_id, joints, is_valid_joints, bbox)


# flip the image & joints 
image_flipped, joints_flipped, is_valid_joints_flipped, bbox_flipped = augment.flip_image_and_joints(image, joints, is_valid_joints, test_dataset.symmetric_joints, bbox)


# plot images & joints
plt.subplot(121)
plt.imshow(image[:,:,::-1])
plt.plot(joints[:,0], joints[:,1], 'or')
plt.title('original image & joints')
plt.subplot(122)
plt.imshow(image_flipped[:,:,::-1])
plt.plot(joints_flipped[:,0], joints_flipped[:,1], 'or')
plt.title('flipped image & joints')


In [ ]:
"""
Another way to plot using bbox and normalized joints

from matplotlib import pyplot as plt
%matplotlib inline

imageIdx = 0   # this image has only upper body
img=test_dataset.get_original_image(imageIdx)


image, joints, is_valid_joints, misc = test_dataset.get_example(imageIdx)
valid_joints = joints[is_valid_joints].reshape(-1,2)

#bbox=misc['orig_tightest_bbox']
bbox=misc['bbox']


# plot joints
plt.imshow(img[:,:,::-1])
# plot joints
offsetX = bbox[0]
offsetY = bbox[1]
W = bbox[2]#-bbox[0]
H = bbox[3]#-bbox[1]
print(W,H)
plt.plot((valid_joints[:,0]+0.5)*W+offsetX, (valid_joints[:,1]+0.5)*H+offsetY,'or')
"""

In [ ]:
len(test_dataset)

#image, joints, is_valid_joints, misc = test_dataset.get_example(0)

In [ ]:
# augment image 


import cv2 as cv

from tools import augment

def augmentByFlip(dataset):
    numImages = len(dataset)
    
    symmetric_joints = dataset.symmetric_joints
    

    for i in {0}:
    #for i in range (numImages):
        # get joints & info
        image_id, joints = dataset.joints[i]
        is_valid_joints, bbox = dataset.info[i]
        print(image_id, joints, is_valid_joints, bbox)
        #print(bbox)

        # get image
        image = dataset.images[image_id]

        image_flipped, joints_flipped, is_valid_joints_flipped, bbox_flipped = augment.flip_image_and_joints(image, joints, is_valid_joints, dataset.symmetric_joints, bbox)
        # below code is moved to tools/augment.py
        
        """
        H, W, C = image.shape
        print(W,H,C)

        # flip image
        image_flipped=cv.flip(image,1)

        # flip joints
        joints_flipped = joints.copy()
        joints_flipped[:,0] = W + 1 - joints_flipped[:,0]
        #print(joint_flipped)
        
        is_valid_joints_flipped = is_valid_joints.copy()
        #print(is_valid_joints_flipped)

        # swap symmetric joints!
        for i, j in symmetric_joints:
            joints_flipped[i], joints_flipped[j] = joints_flipped[j].copy(), joints_flipped[i].copy()
            is_valid_joints_flipped[i], is_valid_joints_flipped[j] = is_valid_joints_flipped[j].copy(), is_valid_joints_flipped[i].copy()
        
        print(joints_flipped)
        print(is_valid_joints_flipped)
        
        # flip bbox
        bbox_flipped = bbox.copy()
        bbox_flipped[0] = W + 1 - (bbox_flipped[0] + bbox_flipped[2])
        print(bbox_flipped)
        """
        

        # add to the dataset
        image_id_flipped = image_id+'_FLR'
        dataset.images[image_id_flipped] = image_flipped

        dataset.joints.append((image_id_flipped, joints_flipped))
        dataset.info.append((is_valid_joints, bbox_flipped))

        
        # plot!
        plt.imshow(image_flipped[:,:,::-1])
        # plot joints
        offsetX = bbox_flipped[0]
        offsetY = bbox_flipped[1]
        W = bbox_flipped[2]
        H = bbox_flipped[3]
        valid_joint_flipped = joints_flipped*is_valid_joints_flipped
        #valid_joint_flipped = joint_flipped[is_valid_joints_flipped]# .reshape(-1,2)
        
        print(valid_joint_flipped)

        plt.clf
        plt.plot(valid_joint_flipped[:,0], valid_joint_flipped[:,1],'or')  # not-normalized
        #plt.plot((valid_joint_flipped[:,0]+0.5)*W+offsetX, (valid_joint_flipped[:,1]+0.5)*H+offsetY,'or')

        
augmentByFlip(test_dataset)

        

In [ ]:
## moved to scripts/dataset.py
print(len(test_dataset))
test_dataset.augmentByFlip()
print(len(test_dataset))

## Next is to apply rotation!

In [ ]:
from tools import augment
%load_ext autoreload
%autoreload 2




imageIdx = 0

image=test_dataset.get_original_image(imageIdx)    
image_id, joints = test_dataset.joints[imageIdx]
is_valid_joints, bbox = test_dataset.info[imageIdx]
print(image_id, joints, is_valid_joints, bbox)


degree = 10
center= joints[12,:] # neck

center_hip = np.mean(joints[2:4,:],axis=0)
print(center_hip)
center_torso =  (center_hip + joints[12,:]) * 0.5
print(center_torso)



# rotate the image & joints 
#image_flipped, joints_flipped, is_valid_joints_flipped, bbox_flipped = augment.flip_image_and_joints(image, joints, is_valid_joints, test_dataset.symmetric_joints, bbox)
image_rotated, joints_rotated, is_valid_joints_rotated = augment.rotate_image_and_joints(image, joints, is_valid_joints, center_torso, degree)

# to test invalid joints
#image_rotated, joints_rotated, is_valid_joints_rotated = augment.rotate_image_and_joints(image, joints, is_valid_joints, (100,150), degree)

print(joints_rotated, is_valid_joints_rotated)


# plot images & joints
plt.subplot(121)
plt.imshow(image[:,:,::-1])
plt.plot(joints[:,0], joints[:,1], 'or')
plt.title('original image & joints')
plt.subplot(122)
plt.imshow(image_rotated[:,:,::-1])
plt.plot(joints_rotated[:,0], joints_rotated[:,1], 'or')
plt.title('rotated image & joints')



In [ ]:
## moved to scripts/dataset.py
print(len(test_dataset))
test_dataset.augmentByRotation((-10,-5,5,10))
print(len(test_dataset))

In [ ]:
for i in range(5):
    plt.subplot(1,5,i+1)
    image, joints, is_valid_joints = test_dataset.get_image_and_joints(i)  # simplified to a method!
    plt.imshow(image[:,:,::-1])
    plt.plot(joints[:,0], joints[:,1], 'or')



In [ ]:
(-10,-5,5,10)

## Next, shift

In [ ]:
# let's test the cropping function

imageIdx = 0

image=test_dataset.get_original_image(imageIdx)    

image_id, joints = test_dataset.joints[imageIdx]
is_valid_joints, bbox = test_dataset.info[imageIdx]
print(image_id, joints, is_valid_joints, bbox)


image_cropped, joints_cropped, bbox_cropped, bbox_origin = test_dataset.apply_cropping(image, joints, bbox, bbox_extension_range=None, shift=None)

print('cropped')
#print(image_id, joints, is_valid_joints, bbox)



In [ ]:

plt.subplot(121)
plt.imshow(image[:,:,::-1])

plt.subplot(122)
plt.imshow(image_cropped[:,:,::-1])
plt.plot(joints_cropped[:,0], joints_cropped[:,1],'or')


In [ ]:
print(image_id, joints, is_valid_joints, bbox)
print(joints_cropped, bbox_cropped, bbox_origin)

## augment shuffled data

In [4]:
from scripts import dataset 

def loadDataset(filename):

    dataset_name = 'met'

    TEST_CV_FILEPATH = '/var/data/MET2/' + filename
    IMG_PATH_PREFIX = '/var/data/MET2'
    symmetric_joints = "[[8, 9], [7, 10], [6, 11], [2, 3], [1, 4], [0, 5]]"
    ignore_label = -1

    print(TEST_CV_FILEPATH)
    print(IMG_PATH_PREFIX)

    test_dataset = dataset.PoseDataset(
        TEST_CV_FILEPATH,
        IMG_PATH_PREFIX, 227,
        fliplr=False, rotate=False,
        shift=None,
        #bbox_extension_range=(1.0, 1.0),
        bbox_extension_range=(1.4, 1.4),
        coord_normalize=True,
        gcn=True,
        fname_index=0,
        joint_index=1,
        symmetric_joints=symmetric_joints,
        ignore_label=ignore_label,
        should_return_bbox=True,
        should_downscale_images=True,
        downscale_height=400
    )
    
    return test_dataset

In [91]:
numClass = 10

for k in range(5):
#for k in range(1):
    train_filename = "activity-met_n{}_ub_train_k{}.csv".format(numClass, k)
    train_dataset = loadDataset(train_filename)
    #print(filename)
    
    val_filename = "activity-met_n{}_ub_val_k{}.csv".format(numClass, k)
    val_dataset = loadDataset(val_filename)
    #print(filename)
    
    print(train_filename)
    print(len(train_dataset))
    print(val_filename)
    print(len(val_dataset))

    
    # augment the training data set by rotation & horizontal flip
    train_dataset.augmentByRotation((-5,5), removeInvalidJoints=False)
    train_dataset.augmentByFlip()
    print(len(train_dataset))
    
    train_filename_augmented = "activity-met_n{}_ub_train_k{}_augmented.csv".format(numClass, k)
    train_dataset.to_csv(train_filename_augmented)
    
    val_dataset.augmentByRotation((-5,5), removeInvalidJoints=False)
    val_dataset.augmentByFlip()
    print(len(val_dataset))
    
    val_filename_augmented = "activity-met_n{}_ub_val_k{}_augmented.csv".format(numClass, k)
    val_dataset.to_csv(val_filename_augmented)
        
    
    
    
    
    
    


16it [00:00, 120.90it/s]

/var/data/MET2/activity-met_n10_ub_train_k0.csv
/var/data/MET2
Reading dataset from /var/data/MET2/activity-met_n10_ub_train_k0.csv
[1] /var/data/MET2/image/office activities/typing/45.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [152. 175.]
 [187. 170.]
 [194.  94.]
 [306.  82.]
 [315. 176.]
 [210. 180.]
 [230.  76.]
 [207.  12.]]
[2] /var/data/MET2/image/office activities/filing.stand/7.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [103. 114.]
 [129. 114.]
 [137.  74.]
 [163.  88.]
 [148. 148.]
 [ 84. 139.]
 [144.  65.]
 [136.  22.]]
[4] /var/data/MET2/image/office activities/reading.seated/15.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 97. 104.]
 [ 75.  99.]
 [ 99.  64.]
 [141.  72.]
 [161.  98.]
 [146. 

70it [00:00, 204.23it/s]

Downscale image/office activities/walking about/22.png to the height 400px
[32] /var/data/MET2/image/office activities/writing/59.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [113. 144.]
 [ 87. 120.]
 [114.  43.]
 [222.  73.]
 [233. 158.]
 [188. 146.]
 [166.  61.]
 [207.   8.]]
Downscale image/office activities/filing.stand/42.jpg to the height 400px
Downscale image/resting/reclining/47.jpg to the height 400px
[40] /var/data/MET2/image/office activities/typing/56.bmp contains non-valid joints
[0 0 1 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ 79. 238.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [199. 204.]
 [124. 215.]
 [100. 120.]
 [111.  90.]
 [144. 178.]
 [196. 188.]
 [137.  95.]
 [170.  49.]]
[41] /var/data/MET2/image/office activities/typing/3.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [1

118it [00:00, 212.79it/s]

Downscale image/office activities/reading.seated/4.jpg to the height 400px
[81] /var/data/MET2/image/office activities/reading.seated/4.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [388. 777.]
 [295. 720.]
 [383. 462.]
 [743. 461.]
 [842. 760.]
 [922. 764.]
 [592. 453.]
 [658. 236.]]
Downscale image/office activities/typing/21.bmp to the height 400px
[83] /var/data/MET2/image/office activities/typing/21.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [363. 336.]
 [456. 379.]
 [506. 206.]
 [540. 253.]
 [418. 417.]
 [303. 331.]
 [493. 178.]
 [407.  69.]]
Downscale image/resting/sleeping/28.jpg to the height 400px
Downscale image/office activities/filing.seated/39.jpg to the height 400px
Downscale image/resting/seated.quiet/27.jpg to the height 400px
Downscale image/resting/reclining/59.jpg to the height 40

187it [00:00, 246.69it/s]

Downscale image/office activities/walking about/54.jpg to the height 400px
[140] /var/data/MET2/image/office activities/walking about/54.jpg contains non-valid joints
[0 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [264. 450.]
 [302. 294.]
 [273. 317.]
 [269. 449.]
 [391. 545.]
 [272. 243.]
 [342. 204.]
 [333. 120.]
 [240. 126.]
 [238. 216.]
 [213. 263.]
 [282.  77.]
 [259.  12.]]
Downscale image/office activities/reading.seated/33.jpg to the height 400px
[142] /var/data/MET2/image/office activities/filing.stand/43.jpg contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [323. 275.]
 [308. 286.]
 [ -1.  -1.]
 [ -1.  -1.]
 [260. 134.]
 [275. 142.]
 [334. 168.]
 [313. 177.]
 [257. 207.]
 [237. 171.]
 [310. 161.]
 [305. 113.]]
[144] /var/data/MET2/image/office activities/reading.seated/53.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [244. 223.]
 [222. 202.]
 [244. 138.]


272it [00:00, 282.95it/s]

Downscale image/resting/seated.quiet/40.jpg to the height 400px
[220] /var/data/MET2/image/office activities/reading.seated/38.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [253. 321.]
 [114. 314.]
 [180. 275.]
 [288. 262.]
 [ -1.  -1.]
 [193. 243.]
 [109. 257.]
 [105. 177.]
 [181. 147.]
 [185. 254.]
 [251. 236.]
 [146. 145.]
 [196.  85.]]
[222] /var/data/MET2/image/office activities/reading.seated/11.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 87. 124.]
 [ 39. 121.]
 [ 43.  71.]
 [122.  72.]
 [141. 114.]
 [173. 123.]
 [ 91.  79.]
 [118.  27.]]
Downscale image/office activities/filing.seated/59.jpg to the height 400px
[226] /var/data/MET2/image/office activities/filing.seated/59.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 78. 453.]
 [105. 610.]
 [370. 392.]
 [854. 523

339it [00:01, 280.14it/s]

Downscale image/office activities/walking about/40.jpg to the height 400px
[287] /var/data/MET2/image/office activities/walking about/40.jpg contains non-valid joints
[0 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [257. 598.]
 [221. 420.]
 [339. 426.]
 [299. 590.]
 [294. 675.]
 [137. 420.]
 [164. 330.]
 [193. 185.]
 [377. 175.]
 [404. 327.]
 [427. 418.]
 [287. 161.]
 [300.  48.]]
[288] /var/data/MET2/image/office activities/filing.seated/28.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [164. 230.]
 [ 53. 225.]
 [101. 199.]
 [183. 231.]
 [ -1.  -1.]
 [182. 160.]
 [129. 190.]
 [ 85. 121.]
 [132. 115.]
 [162. 141.]
 [200. 140.]
 [119.  97.]
 [140.  59.]]
[290] /var/data/MET2/image/office activities/reading.seated/3.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [121. 133.]
 [ 70. 127.]
 [115.  81.]
 [174.  80.]
 [218. 131.]
 [174. 131.]
 [146.  84.]
 [141.  32.]]
Downscale 

380it [00:01, 276.70it/s]
0it [00:00, ?it/s]

[340] /var/data/MET2/image/office activities/typing/60.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [ 9.690e+02  8.390e+02]
 [ 4.840e+02  9.590e+02]
 [ 3.910e+02  5.290e+02]
 [ 7.990e+02  4.880e+02]
 [ 8.830e+02  7.400e+02]
 [ 1.171e+03  8.040e+02]
 [ 7.320e+02  5.120e+02]
 [ 8.660e+02  2.540e+02]]
Downscale image/resting/seated.quiet/51.jpg to the height 400px
[345] /var/data/MET2/image/office activities/reading.seated/54.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [165. 207.]
 [222. 213.]
 [233. 149.]
 [327. 156.]
 [313. 275.]
 [214. 222.]
 [270. 143.]
 [218.  60.]]
Downscale image/office activities/walking about/25.png to the height 400px
Downscale image/office activities/typing/22.bmp to the height 400px
[349] /var/data/MET2/

45it [00:00, 192.85it/s]

Downscale image/office activities/walking about/39.jpg to the height 400px
[10] /var/data/MET2/image/office activities/typing/18.bmp contains non-valid joints
[0 1 0 0 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 87. 134.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 99. 144.]
 [ -1.  -1.]
 [132. 121.]
 [156. 113.]
 [158.  70.]
 [203.  68.]
 [190. 129.]
 [150. 130.]
 [174.  59.]
 [149.  29.]]
Downscale image/office activities/typing/23.bmp to the height 400px
[11] /var/data/MET2/image/office activities/typing/23.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [ 1.051e+03  9.080e+02]
 [ 1.135e+03  7.530e+02]
 [ 1.238e+03  4.620e+02]
 [ 1.778e+03  4.960e+02]
 [ 1.766e+03  9.380e+02]
 [ 1.348e+03  9.610e+02]
 [ 1.408e+03  4.930e+02]
 [ 1.404e+03  1.850e+02]]
Downscale image/resting/seated.quiet/59.jpg to the height 400px
[17] /var/data/MET2/image/offic

94it [00:00, 206.35it/s]

Downscale image/office activities/typing/26.bmp to the height 400px
[47] /var/data/MET2/image/office activities/typing/26.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [ 1.483e+03  2.314e+03]
 [ 8.640e+02  2.143e+03]
 [ 1.033e+03  1.222e+03]
 [ 2.217e+03  1.174e+03]
 [ 2.319e+03  2.016e+03]
 [ 2.241e+03  2.218e+03]
 [ 1.657e+03  1.171e+03]
 [ 1.632e+03  3.430e+02]]
Downscale image/office activities/reading.seated/43.jpg to the height 400px
[50] /var/data/MET2/image/office activities/typing/25.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [340. 322.]
 [272. 288.]
 [322. 150.]
 [500. 135.]
 [571. 283.]
 [494. 321.]
 [415. 151.]
 [415.   8.]]
[53] /var/data/MET2/image/office activities/writing/16.bmp contains non-valid joints
[0 0 0 0 

96it [00:00, 200.71it/s]


Downscale image/office activities/walking about/58.png to the height 400px
[94] /var/data/MET2/image/office activities/walking about/58.png contains non-valid joints
[1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[453. 753.]
 [443. 676.]
 [408. 454.]
 [548. 454.]
 [512. 671.]
 [ -1.  -1.]
 [365. 337.]
 [391. 361.]
 [399. 211.]
 [600. 228.]
 [583. 388.]
 [586. 501.]
 [500. 169.]
 [494.  44.]]
Downscale image/office activities/reading.seated/34.jpg to the height 400px
96 images loaded
joints shape: (14, 2)
activity-met_n10_ub_train_k0.csv
380
activity-met_n10_ub_val_k0.csv
96
[Warning] During rotation, joint [17.64705882  6.53594771] becomes invalid [25.06495689 -0.61675972].
[Warning] During rotation, joint [207.   8.] becomes invalid [204.60881357  -2.76717333].
[Warning] During rotation, joint [233. 158.] becomes invalid [221.27136699 170.62986064].
[Warning] During rotation, joint [235.55555556   4.44444444] becomes invalid [230.50086228  -7.32706861].
[Warning] During rotation, joint [  0. 277.] be

38it [00:00, 364.22it/s]

[Warning] During rotation, joint [228.10457516   0.65359477] becomes invalid [217.72740356  -0.74820461].
[Warning] During rotation, joint [163.   3.] becomes invalid [159.08966223  -5.56145955].
576
/var/data/MET2/activity-met_n10_ub_train_k1.csv
/var/data/MET2
Reading dataset from /var/data/MET2/activity-met_n10_ub_train_k1.csv
Downscale image/resting/reclining/27.jpg to the height 400px
[1] /var/data/MET2/image/office activities/writing/15.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [102. 110.]
 [ 46. 102.]
 [ 69.  57.]
 [147.  60.]
 [188.  93.]
 [170. 110.]
 [114.  53.]
 [144.  16.]]
[3] /var/data/MET2/image/office activities/filing.stand/2.bmp contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [210. 128.]
 [191. 129.]
 [ -1.  -1.]
 [ -1.  -1.]
 [171.  35.]
 [193.  45.]
 [213.  42.]
 [205.  48.]
 [169.  63.]
 [154.  52.]
 [203.  36.]
 [194.   5.]]
Downscale

59it [00:00, 279.33it/s]

Downscale image/office activities/filing.seated/41.jpg to the height 400px
[43] /var/data/MET2/image/office activities/filing.seated/41.jpg contains non-valid joints
[0 1 0 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [313. 789.]
 [ -1.  -1.]
 [791. 922.]
 [ -1.  -1.]
 [ -1.  -1.]
 [458. 420.]
 [527. 526.]
 [631. 376.]
 [857. 482.]
 [647. 793.]
 [385. 637.]
 [768. 335.]
 [615.  45.]]
Downscale image/office activities/walking about/34.png to the height 400px
Downscale image/office activities/typing/39.bmp to the height 400px
[47] /var/data/MET2/image/office activities/typing/39.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [500. 434.]
 [406. 428.]
 [444. 244.]
 [775. 235.]
 [900. 438.]
 [732. 453.]
 [583. 218.]
 [546.  52.]]
[48] /var/data/MET2/image/office activities/writing/49.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]


109it [00:00, 254.25it/s]

Downscale image/office activities/walking about/26.png to the height 400px
[88] /var/data/MET2/image/office activities/filing.stand/43.jpg contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [323. 275.]
 [308. 286.]
 [ -1.  -1.]
 [ -1.  -1.]
 [260. 134.]
 [275. 142.]
 [334. 168.]
 [313. 177.]
 [257. 207.]
 [237. 171.]
 [310. 161.]
 [305. 113.]]
[90] /var/data/MET2/image/office activities/writing/20.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [126. 133.]
 [142. 122.]
 [186.  92.]
 [250.  92.]
 [221. 165.]
 [165. 147.]
 [206.  73.]
 [186.  24.]]
Downscale image/office activities/walking about/25.png to the height 400px
[93] /var/data/MET2/image/office activities/typing/56.bmp contains non-valid joints
[0 0 1 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ 79. 238.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [199. 204.]
 [124. 215.]
 [100. 120.]
 [111.  90.]
 [14

153it [00:00, 229.52it/s]

Downscale image/office activities/reading.seated/24.png to the height 400px
[133] /var/data/MET2/image/office activities/reading.seated/24.png contains non-valid joints
[0 1 0 0 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [778. 778.]
 [ -1.  -1.]
 [ -1.  -1.]
 [693. 749.]
 [ -1.  -1.]
 [859. 533.]
 [773. 695.]
 [573. 524.]
 [350. 366.]
 [467. 577.]
 [707. 571.]
 [539. 380.]
 [599. 148.]]
Downscale image/office activities/typing/44.bmp to the height 400px
[135] /var/data/MET2/image/office activities/typing/44.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [420. 396.]
 [256. 401.]
 [257. 196.]
 [467. 177.]
 [525. 310.]
 [530. 366.]
 [386. 190.]
 [405.  77.]]
Downscale image/resting/seated.quiet/40.jpg to the height 400px
Downscale image/office activities/walking about/45.png to the height 400px
Downscale image/resting/reclining/38.jpg to the height 400px
Downscale image/resting/seated.quiet/23.jpg to the h

216it [00:00, 241.93it/s]

Downscale image/office activities/walking about/31.png to the height 400px
[173] /var/data/MET2/image/office activities/filing.seated/60.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [147. 196.]
 [ 96. 176.]
 [126. 162.]
 [147. 171.]
 [ -1.  -1.]
 [157. 128.]
 [130. 129.]
 [ 93.  93.]
 [134.  99.]
 [137. 119.]
 [163. 118.]
 [117.  81.]
 [136.  41.]]
[174] /var/data/MET2/image/office activities/reading.seated/15.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 97. 104.]
 [ 75.  99.]
 [ 99.  64.]
 [141.  72.]
 [161.  98.]
 [146.  99.]
 [121.  73.]
 [128.  39.]]
Downscale image/office activities/typing/58.bmp to the height 400px
[175] /var/data/MET2/image/office activities/typing/58.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [497. 417.]
 [304. 414.]
 [279. 206.]
 [522. 214.]
 

288it [00:01, 261.00it/s]

Downscale image/office activities/filing.stand/59.PNG to the height 400px
[243] /var/data/MET2/image/office activities/filing.stand/59.PNG contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [275. 238.]
 [236. 331.]
 [137. 272.]
 [152. 237.]
 [240. 219.]
 [269. 161.]
 [138. 211.]
 [143. 125.]]
[245] /var/data/MET2/image/office activities/typing/43.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [168. 170.]
 [210. 170.]
 [234. 104.]
 [275. 101.]
 [238. 207.]
 [170. 181.]
 [234.  89.]
 [206.  42.]]
Downscale image/office activities/filing.seated/52.jpg to the height 400px
[246] /var/data/MET2/image/office activities/filing.seated/52.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [800. 655.]
 [699. 508.]
 [896. 505.]
 [742. 568.]
 [ -1.  -1.]
 [515. 477.]
 [625. 390.]
 [670. 266.]
 [937. 294

345it [00:01, 256.21it/s]

Downscale image/office activities/reading.seated/30.jpg to the height 400px
Downscale image/office activities/walking about/39.jpg to the height 400px
[313] /var/data/MET2/image/office activities/writing/14.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 96. 116.]
 [ 10. 113.]
 [ 56.  36.]
 [143.  76.]
 [224. 105.]
 [193.  95.]
 [112.  66.]
 [156.  12.]]
Downscale image/office activities/typing/36.bmp to the height 400px
[315] /var/data/MET2/image/office activities/typing/36.bmp contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [545. 788.]
 [311. 754.]
 [412. 662.]
 [585. 743.]
 [ -1.  -1.]
 [539. 535.]
 [365. 644.]
 [269. 356.]
 [303. 274.]
 [374. 552.]
 [518. 507.]
 [376. 287.]
 [463. 138.]]
[316] /var/data/MET2/image/office activities/reading.seated/20.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  

380it [00:01, 265.72it/s]
33it [00:00, 324.99it/s]

[354] /var/data/MET2/image/office activities/writing/2.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 73. 144.]
 [  3. 139.]
 [ 34.  64.]
 [132.  80.]
 [152. 146.]
 [113. 111.]
 [ 78.  68.]
 [108.  19.]]
Downscale image/resting/reclining/50.jpg to the height 400px
[356] /var/data/MET2/image/office activities/writing/21.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [150. 157.]
 [ 65. 146.]
 [ 98.  81.]
 [197.  83.]
 [230. 149.]
 [227.  79.]
 [145.  88.]
 [167.  24.]]
Downscale image/office activities/filing.stand/41.jpg to the height 400px
[357] /var/data/MET2/image/office activities/filing.stand/41.jpg contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [356. 520.]
 [409. 515.]
 [ -1.  -1.]
 [ -1.  -1.]
 [268. 291.]
 [333. 361.]
 [392. 268.]
 [402. 284.]
 [318. 368.]
 [

83it [00:00, 257.73it/s]

Downscale image/office activities/walking about/21.png to the height 400px
Downscale image/office activities/reading.seated/59.jpg to the height 400px
[49] /var/data/MET2/image/office activities/reading.seated/59.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [264. 476.]
 [361. 622.]
 [477. 468.]
 [611. 532.]
 [357. 703.]
 [282. 465.]
 [511. 420.]
 [523. 236.]]
Downscale image/resting/reclining/43.jpg to the height 400px
[52] /var/data/MET2/image/office activities/writing/60.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [148.  96.]
 [115. 133.]
 [108.  78.]
 [181.  63.]
 [194. 104.]
 [200. 128.]
 [147.  64.]
 [139.   8.]]
[55] /var/data/MET2/image/office activities/writing/32.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 

96it [00:00, 246.93it/s]


Downscale image/resting/seated.quiet/21.jpg to the height 400px
96 images loaded
joints shape: (14, 2)
activity-met_n10_ub_train_k1.csv
380
activity-met_n10_ub_val_k1.csv
96
[Warning] During rotation, joint [  4. 261.] becomes invalid [-12.60378994 253.28931201].
[Warning] During rotation, joint [142.   3.] becomes invalid [139.23637164  -3.29749599].
[Warning] During rotation, joint [462.5 395. ] becomes invalid [435.49232762 413.57739622].
[Warning] During rotation, joint [205.3125 366.875 ] becomes invalid [224.10941757 356.92644298].
[Warning] During rotation, joint [  0.  237.6] becomes invalid [ -1.1519909  225.18492343].
[Warning] During rotation, joint [355.83333333   0.        ] becomes invalid [373.55172331  -2.90119353].
[Warning] During rotation, joint [625.         379.16666667] becomes invalid [597.47068389 409.6916635 ].
[Warning] During rotation, joint [  0.         238.29787234] becomes invalid [ -4.02826107 208.43255349].
[Warning] During rotation, joint [334. 287.] b

32it [00:00, 254.27it/s]

[Warning] During rotation, joint [  6. 124.] becomes invalid [ -2.33080094 122.80671146].
[Warning] During rotation, joint [ 3. 68.] becomes invalid [-0.43866344 66.75834114].
[Warning] During rotation, joint [200. 179.] becomes invalid [190.20588137 186.32219691].
576
/var/data/MET2/activity-met_n10_ub_train_k2.csv
/var/data/MET2
Reading dataset from /var/data/MET2/activity-met_n10_ub_train_k2.csv
Downscale image/resting/reclining/50.jpg to the height 400px
Downscale image/resting/seated.quiet/53.jpg to the height 400px
[5] /var/data/MET2/image/office activities/reading.seated/20.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 99. 137.]
 [ 89. 135.]
 [116.  76.]
 [189.  75.]
 [207. 143.]
 [167. 110.]
 [145.  73.]
 [129.  31.]]
Downscale image/office activities/typing/7.bmp to the height 400px
[6] /var/data/MET2/image/office activities/typing/7.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1

59it [00:00, 252.65it/s]

Downscale image/office activities/filing.stand/59.PNG to the height 400px
[36] /var/data/MET2/image/office activities/filing.stand/59.PNG contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [275. 238.]
 [236. 331.]
 [137. 272.]
 [152. 237.]
 [240. 219.]
 [269. 161.]
 [138. 211.]
 [143. 125.]]
[37] /var/data/MET2/image/office activities/reading.seated/11.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 87. 124.]
 [ 39. 121.]
 [ 43.  71.]
 [122.  72.]
 [141. 114.]
 [173. 123.]
 [ 91.  79.]
 [118.  27.]]
Downscale image/office activities/walking about/58.png to the height 400px
[38] /var/data/MET2/image/office activities/walking about/58.png contains non-valid joints
[1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[453. 753.]
 [443. 676.]
 [408. 454.]
 [548. 454.]
 [512. 671.]
 [ -1.  -1.]
 [365. 337.]
 [391. 361.]
 [399. 211.]
 [600

105it [00:00, 227.30it/s]

[85] /var/data/MET2/image/office activities/writing/41.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [115. 128.]
 [ 77. 119.]
 [116.  68.]
 [187.  82.]
 [200. 125.]
 [209.  76.]
 [160.  69.]
 [145.  18.]]
[86] /var/data/MET2/image/office activities/reading.seated/10.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [101. 133.]
 [115. 126.]
 [107.  78.]
 [185.  73.]
 [173. 120.]
 [174. 142.]
 [138.  64.]
 [142.   3.]]
Downscale image/office activities/filing.seated/39.jpg to the height 400px
Downscale image/office activities/typing/30.bmp to the height 400px
[88] /var/data/MET2/image/office activities/typing/30.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [454. 395.]
 [519. 370.]
 [559. 202.]
 [757. 229.]
 [750. 45

144it [00:00, 215.81it/s]

Downscale image/resting/sleeping/26.jpg to the height 400px
Downscale image/office activities/typing/32.bmp to the height 400px
[121] /var/data/MET2/image/office activities/typing/32.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [429. 454.]
 [260. 469.]
 [263. 272.]
 [416. 225.]
 [440. 344.]
 [479. 406.]
 [390. 250.]
 [455. 134.]]
Downscale image/office activities/typing/39.bmp to the height 400px
[122] /var/data/MET2/image/office activities/typing/39.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [500. 434.]
 [406. 428.]
 [444. 244.]
 [775. 235.]
 [900. 438.]
 [732. 453.]
 [583. 218.]
 [546.  52.]]
[124] /var/data/MET2/image/office activities/writing/50.jpeg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [213. 165.]
 [ 95. 165.]
 [130. 154.]
 [206. 167.]
 [ -1.  -1.]
 [115. 116.]


187it [00:00, 208.91it/s]

Downscale image/office activities/walking about/21.png to the height 400px
[152] /var/data/MET2/image/office activities/writing/57.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 40. 184.]
 [ 25. 180.]
 [ 67. 127.]
 [163. 129.]
 [186. 174.]
 [128. 187.]
 [121. 130.]
 [119.  40.]]
[154] /var/data/MET2/image/office activities/reading.seated/51.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [184. 228.]
 [107. 252.]
 [ 73. 162.]
 [171.  83.]
 [222. 160.]
 [277. 171.]
 [126. 108.]
 [132.  42.]]
[157] /var/data/MET2/image/office activities/reading.seated/60.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [121. 187.]
 [  4. 261.]
 [ 78. 141.]
 [216. 164.]
 [248. 274.]
 [322. 230.]
 [169. 135.]
 [192.  40.]]
Downscale ima

260it [00:01, 232.53it/s]

Downscale image/office activities/walking about/30.png to the height 400px
[205] /var/data/MET2/image/office activities/typing/43.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [168. 170.]
 [210. 170.]
 [234. 104.]
 [275. 101.]
 [238. 207.]
 [170. 181.]
 [234.  89.]
 [206.  42.]]
[209] /var/data/MET2/image/office activities/typing/52.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [195. 195.]
 [266. 191.]
 [336. 109.]
 [360. 127.]
 [276. 220.]
 [176. 207.]
 [320.  95.]
 [296.  32.]]
[210] /var/data/MET2/image/office activities/writing/56.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [110. 146.]
 [ 81. 144.]
 [126.  96.]
 [205. 102.]
 [222. 152.]
 [208. 153.]
 [161.  89.]
 [163.  32.]]
[212] /var/data/MET2/image/of

287it [00:01, 224.09it/s]

Downscale image/office activities/reading.seated/58.png to the height 400px
[272] /var/data/MET2/image/office activities/reading.seated/58.png contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [504. 688.]
 [263. 546.]
 [423. 380.]
 [724. 429.]
 [917. 619.]
 [674. 648.]
 [578. 467.]
 [691. 351.]]
Downscale image/office activities/walking about/57.png to the height 400px
Downscale image/office activities/filing.seated/26.jpg to the height 400px
[274] /var/data/MET2/image/office activities/filing.seated/26.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [214. 222.]
 [299. 265.]
 [376. 237.]
 [498. 237.]
 [425. 390.]
 [394. 278.]
 [445. 201.]
 [370.  91.]]
[275] /var/data/MET2/image/office activities/filing.seated/11.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [

380it [00:01, 245.02it/s]
0it [00:00, ?it/s]

Downscale image/resting/seated.quiet/36.jpg to the height 400px
Downscale image/office activities/typing/50.bmp to the height 400px
[320] /var/data/MET2/image/office activities/typing/50.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [372. 562.]
 [513. 554.]
 [521. 303.]
 [818. 315.]
 [796. 648.]
 [546. 602.]
 [585. 304.]
 [506. 145.]]
[321] /var/data/MET2/image/resting/reclining/20.png contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 46.  85.]
 [115. 132.]
 [159. 158.]
 [ 53. 111.]
 [ -1.  -1.]
 [128. 102.]
 [133. 113.]
 [210.  76.]
 [267.  90.]
 [225. 148.]
 [180. 113.]
 [245.  66.]
 [255.  25.]]
[322] /var/data/MET2/image/office activities/typing/28.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [305. 250.]
 [367. 248.]
 [386. 167.]
 [423. 184.]
 [374. 282.]
 [288. 271.]
 [361. 1

46it [00:00, 284.02it/s]

[11] /var/data/MET2/image/office activities/writing/44.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 99. 144.]
 [ 50. 153.]
 [ 46.  76.]
 [120.  76.]
 [150. 112.]
 [172. 111.]
 [ 90.  75.]
 [119.  23.]]
[13] /var/data/MET2/image/office activities/typing/45.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [152. 175.]
 [187. 170.]
 [194.  94.]
 [306.  82.]
 [315. 176.]
 [210. 180.]
 [230.  76.]
 [207.  12.]]
Downscale image/office activities/typing/1.bmp to the height 400px
[14] /var/data/MET2/image/office activities/typing/1.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [389. 389.]
 [471. 356.]
 [487. 223.]
 [649. 234.]
 [590. 403.]
 [461. 406.]
 [551. 219.]
 [516.  86.]]
Downscale image/office activities/filing.

96it [00:00, 278.12it/s]


[59] /var/data/MET2/image/office activities/filing.seated/56.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [184. 202.]
 [128. 232.]
 [182. 140.]
 [341. 114.]
 [437. 252.]
 [381. 231.]
 [277. 114.]
 [196.  58.]]
Downscale image/resting/sleeping/48.jpg to the height 400px
[63] /var/data/MET2/image/office activities/filing.stand/48.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [189. 386.]
 [202. 306.]
 [169. 304.]
 [167. 388.]
 [ -1.  -1.]
 [101.  89.]
 [130. 100.]
 [208. 131.]
 [182. 158.]
 [116. 209.]
 [ 70. 142.]
 [174. 130.]
 [183.  61.]]
Downscale image/resting/reclining/38.jpg to the height 400px
Downscale image/office activities/reading.seated/37.jpg to the height 400px
[65] /var/data/MET2/image/office activities/reading.seated/37.jpg contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [ 2.610e+02  1.055e+03]

[Warning] During rotation, joint [465.49707602 378.94736842] becomes invalid [439.06976682 403.53050364].
[Warning] During rotation, joint [  0.  237.6] becomes invalid [ -1.1519909  225.18492343].
[Warning] During rotation, joint [200. 179.] becomes invalid [190.20588137 186.32219691].
2280


0it [00:00, ?it/s]

[Warning] During rotation, joint [ 6. 18.] becomes invalid [-0.4280465 21.77353  ].
[Warning] During rotation, joint [355.83333333   0.        ] becomes invalid [373.55172331  -2.90119353].
[Warning] During rotation, joint [  0.         238.29787234] becomes invalid [ -4.02826107 208.43255349].
[Warning] During rotation, joint [415.   8.] becomes invalid [408.36906244  -9.87343926].
[Warning] During rotation, joint [437. 252.] becomes invalid [452.90116244 225.1964964 ].
[Warning] During rotation, joint [334. 287.] becomes invalid [313.15923727 302.33194341].
[Warning] During rotation, joint [177. 167.] becomes invalid [185.78471056 171.7029511 ].
[Warning] During rotation, joint [165.   1.] becomes invalid [171.17212403  -4.86488172].
[Warning] During rotation, joint [163.   3.] becomes invalid [159.08966223  -5.56145955].
576
/var/data/MET2/activity-met_n10_ub_train_k3.csv
/var/data/MET2
Reading dataset from /var/data/MET2/activity-met_n10_ub_train_k3.csv
Downscale image/office activ

43it [00:00, 204.87it/s]

Downscale image/office activities/typing/34.bmp to the height 400px
[15] /var/data/MET2/image/office activities/typing/34.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [642. 732.]
 [335. 786.]
 [241. 479.]
 [479. 466.]
 [531. 703.]
 [747. 683.]
 [441. 449.]
 [565. 286.]]
[16] /var/data/MET2/image/office activities/writing/56.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [110. 146.]
 [ 81. 144.]
 [126.  96.]
 [205. 102.]
 [222. 152.]
 [208. 153.]
 [161.  89.]
 [163.  32.]]
Downscale image/office activities/filing.seated/52.jpg to the height 400px
[17] /var/data/MET2/image/office activities/filing.seated/52.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [800. 655.]
 [699. 508.]
 [896. 505.]
 [742. 568.]
 [ -1.  -1.]
 [515. 477.]
 [625. 390.]
 [670. 266.]
 [937. 294.]
 [844. 478

105it [00:00, 252.97it/s]

Downscale image/office activities/walking about/58.png to the height 400px
[57] /var/data/MET2/image/office activities/walking about/58.png contains non-valid joints
[1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[453. 753.]
 [443. 676.]
 [408. 454.]
 [548. 454.]
 [512. 671.]
 [ -1.  -1.]
 [365. 337.]
 [391. 361.]
 [399. 211.]
 [600. 228.]
 [583. 388.]
 [586. 501.]
 [500. 169.]
 [494.  44.]]
Downscale image/resting/seated.quiet/27.jpg to the height 400px
Downscale image/office activities/walking about/36.png to the height 400px
Downscale image/office activities/filing.seated/38.jpg to the height 400px
[61] /var/data/MET2/image/office activities/filing.seated/38.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [249. 434.]
 [103. 413.]
 [188. 362.]
 [341. 376.]
 [ -1.  -1.]
 [170. 315.]
 [ 63. 326.]
 [ 54. 217.]
 [150. 199.]
 [186. 246.]
 [260. 236.]
 [118. 184.]
 [101.  92.]]
Downscale image/office activities/filing.stand/41.jpg to the height 400px
[62] /var/data/MET2/image/off

167it [00:00, 259.87it/s]

[114] /var/data/MET2/image/resting/reclining/20.png contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 46.  85.]
 [115. 132.]
 [159. 158.]
 [ 53. 111.]
 [ -1.  -1.]
 [128. 102.]
 [133. 113.]
 [210.  76.]
 [267.  90.]
 [225. 148.]
 [180. 113.]
 [245.  66.]
 [255.  25.]]
[115] /var/data/MET2/image/office activities/typing/31.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [186. 208.]
 [ 51. 236.]
 [ 41.  97.]
 [173.  71.]
 [206. 173.]
 [256. 181.]
 [127.  88.]
 [163.   3.]]
[116] /var/data/MET2/image/office activities/filing.seated/11.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 76.  99.]
 [ 98.  96.]
 [102.  52.]
 [158.  56.]
 [140. 104.]
 [113. 112.]
 [130.  48.]
 [129.   8.]]
Downscale image/resting/seated.quiet/23.jpg to the height 400px
[120] /var/data/MET2/image/office activiti

203it [00:00, 252.94it/s]

[174] /var/data/MET2/image/office activities/typing/1.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [389. 389.]
 [471. 356.]
 [487. 223.]
 [649. 234.]
 [590. 403.]
 [461. 406.]
 [551. 219.]
 [516.  86.]]
Downscale image/office activities/typing/49.bmp to the height 400px
[176] /var/data/MET2/image/office activities/typing/49.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [324. 349.]
 [460. 357.]
 [619. 208.]
 [723. 283.]
 [555. 474.]
 [341. 383.]
 [568. 229.]
 [530.  72.]]
Downscale image/office activities/walking about/49.png to the height 400px
Downscale image/office activities/walking about/48.png to the height 400px
Downscale image/office activities/filing.stand/56.PNG to the height 400px
[183] /var/data/MET2/image/office activities/writing/16.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 

268it [00:01, 264.43it/s]

Downscale image/office activities/reading.seated/21.jpg to the height 400px
[223] /var/data/MET2/image/office activities/reading.seated/21.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [305. 549.]
 [235. 789.]
 [219. 531.]
 [547. 488.]
 [634. 776.]
 [381. 788.]
 [390. 557.]
 [306. 346.]]
Downscale image/office activities/filing.seated/53.jpg to the height 400px
[224] /var/data/MET2/image/office activities/filing.seated/53.jpg contains non-valid joints
[1 1 1 0 1 1 1 1 1 1 1 1 1 1]
[[417. 324.]
 [381. 215.]
 [588. 194.]
 [ -1.  -1.]
 [472. 221.]
 [451. 369.]
 [299. 283.]
 [374. 197.]
 [421. 135.]
 [512.  89.]
 [494. 193.]
 [416. 206.]
 [462.  93.]
 [423.  12.]]
Downscale image/resting/reclining/48.jpg to the height 400px
Downscale image/office activities/walking about/53.jpg to the height 400px
Downscale image/office activities/walking about/57.png to the height 400px
[230] /var/data/MET2/image/

329it [00:01, 268.57it/s]

Downscale image/resting/standing.relaxed/5.bmp to the height 400px
[284] /var/data/MET2/image/office activities/typing/16.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 77. 131.]
 [ 48. 116.]
 [ 64.  63.]
 [121.  61.]
 [136. 107.]
 [140. 131.]
 [ 95.  60.]
 [101.  28.]]
[285] /var/data/MET2/image/office activities/writing/44.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 99. 144.]
 [ 50. 153.]
 [ 46.  76.]
 [120.  76.]
 [150. 112.]
 [172. 111.]
 [ 90.  75.]
 [119.  23.]]
Downscale image/resting/seated.quiet/30.jpg to the height 400px
Downscale image/office activities/filing.stand/59.PNG to the height 400px
[287] /var/data/MET2/image/office activities/filing.stand/59.PNG contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.

380it [00:01, 275.01it/s]
0it [00:00, ?it/s]

[335] /var/data/MET2/image/office activities/filing.seated/43.jpg contains non-valid joints
[0 1 0 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 82. 155.]
 [ -1.  -1.]
 [ 94. 161.]
 [200. 179.]
 [ -1.  -1.]
 [127.  92.]
 [137. 112.]
 [148.  72.]
 [213.  78.]
 [178. 143.]
 [121. 148.]
 [176.  61.]
 [155.  14.]]
[337] /var/data/MET2/image/resting/seated.quiet/24.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 98. 289.]
 [ 99. 253.]
 [168. 250.]
 [164. 287.]
 [ -1.  -1.]
 [ 85. 247.]
 [ 48. 201.]
 [ 78. 127.]
 [188. 123.]
 [209. 200.]
 [184. 242.]
 [132. 101.]
 [133.  45.]]
Downscale image/resting/seated.quiet/35.jpg to the height 400px
Downscale image/resting/reclining/31.jpg to the height 400px
Downscale image/office activities/filing.stand/32.jpg to the height 400px
[347] /var/data/MET2/image/office activities/reading.seated/60.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 

72it [00:00, 351.31it/s]

[40] /var/data/MET2/image/office activities/reading.seated/54.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [165. 207.]
 [222. 213.]
 [233. 149.]
 [327. 156.]
 [313. 275.]
 [214. 222.]
 [270. 143.]
 [218.  60.]]
Downscale image/resting/sleeping/26.jpg to the height 400px
[45] /var/data/MET2/image/office activities/typing/25.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [340. 322.]
 [272. 288.]
 [322. 150.]
 [500. 135.]
 [571. 283.]
 [494. 321.]
 [415. 151.]
 [415.   8.]]
[46] /var/data/MET2/image/office activities/writing/14.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 96. 116.]
 [ 10. 113.]
 [ 56.  36.]
 [143.  76.]
 [224. 105.]
 [193.  95.]
 [112.  66.]
 [156.  12.]]
Downscale image/office activities/walki

96it [00:00, 271.20it/s]


[84] /var/data/MET2/image/office activities/typing/26.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [-1.000e+00 -1.000e+00]
 [ 1.483e+03  2.314e+03]
 [ 8.640e+02  2.143e+03]
 [ 1.033e+03  1.222e+03]
 [ 2.217e+03  1.174e+03]
 [ 2.319e+03  2.016e+03]
 [ 2.241e+03  2.218e+03]
 [ 1.657e+03  1.171e+03]
 [ 1.632e+03  3.430e+02]]
Downscale image/resting/reclining/47.jpg to the height 400px
Downscale image/resting/reclining/30.jpg to the height 400px
Downscale image/resting/reclining/17.png to the height 400px
Downscale image/office activities/filing.stand/54.jpg to the height 400px
[93] /var/data/MET2/image/office activities/reading.seated/13.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 46. 140.]
 [ 23. 133.]
 [ 26.  81.]
 [ 84.  84.]
 [ 88. 119.]
 [102. 128.]


27it [00:00, 266.81it/s]

[Warning] During rotation, joint [164. 230.] becomes invalid [157.1685915  235.46497873].
[Warning] During rotation, joint [183. 231.] becomes invalid [176.00913502 238.11713254].
[Warning] During rotation, joint [  0. 277.] becomes invalid [ -5.71093019 257.80180618].
[Warning] During rotation, joint [169. 253.] becomes invalid [160.55384985 260.94864274].
576
/var/data/MET2/activity-met_n10_ub_train_k4.csv
/var/data/MET2
Reading dataset from /var/data/MET2/activity-met_n10_ub_train_k4.csv
[1] /var/data/MET2/image/office activities/typing/18.bmp contains non-valid joints
[0 1 0 0 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 87. 134.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 99. 144.]
 [ -1.  -1.]
 [132. 121.]
 [156. 113.]
 [158.  70.]
 [203.  68.]
 [190. 129.]
 [150. 130.]
 [174.  59.]
 [149.  29.]]
[5] /var/data/MET2/image/office activities/writing/12.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [142. 152.]
 [

70it [00:00, 230.95it/s]

[31] /var/data/MET2/image/office activities/typing/45.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [152. 175.]
 [187. 170.]
 [194.  94.]
 [306.  82.]
 [315. 176.]
 [210. 180.]
 [230.  76.]
 [207.  12.]]
[34] /var/data/MET2/image/office activities/typing/11.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [112. 120.]
 [120. 102.]
 [138.  64.]
 [195.  78.]
 [211. 146.]
 [155. 149.]
 [156.  65.]
 [151.  14.]]
Downscale image/office activities/reading.seated/33.jpg to the height 400px
Downscale image/office activities/walking about/21.png to the height 400px
[40] /var/data/MET2/image/office activities/writing/54.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 84. 121.]
 [107. 115.]
 [145.  87.]
 [200.  85.]
 [208. 13

130it [00:00, 255.47it/s]

[71] /var/data/MET2/image/office activities/filing.stand/2.bmp contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [210. 128.]
 [191. 129.]
 [ -1.  -1.]
 [ -1.  -1.]
 [171.  35.]
 [193.  45.]
 [213.  42.]
 [205.  48.]
 [169.  63.]
 [154.  52.]
 [203.  36.]
 [194.   5.]]
[72] /var/data/MET2/image/office activities/filing.seated/36.jpg contains non-valid joints
[1 0 0 1 1 1 1 1 1 1 1 1 1 1]
[[ 70. 232.]
 [ -1.  -1.]
 [ -1.  -1.]
 [158. 157.]
 [ 76. 148.]
 [ 96. 229.]
 [ 44. 124.]
 [ 83. 110.]
 [103.  75.]
 [154.  69.]
 [125. 130.]
 [ 75. 129.]
 [122.  58.]
 [ 93.  19.]]
Downscale image/office activities/typing/7.bmp to the height 400px
[74] /var/data/MET2/image/office activities/typing/7.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 95. 403.]
 [ 46. 386.]
 [ 47. 267.]
 [223. 255.]
 [231. 356.]
 [238. 400.]
 [124. 231.]
 [127. 143.]]
Downscale image/resting/reclini

189it [00:00, 266.24it/s]

[131] /var/data/MET2/image/office activities/filing.seated/11.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 76.  99.]
 [ 98.  96.]
 [102.  52.]
 [158.  56.]
 [140. 104.]
 [113. 112.]
 [130.  48.]
 [129.   8.]]
[135] /var/data/MET2/image/office activities/writing/33.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [154. 136.]
 [ 93. 156.]
 [ 92.  91.]
 [141.  94.]
 [171. 122.]
 [186. 126.]
 [125.  75.]
 [162.  26.]]
Downscale image/office activities/walking about/26.png to the height 400px
[137] /var/data/MET2/image/office activities/typing/27.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [157. 167.]
 [247. 161.]
 [332. 100.]
 [355. 126.]
 [242. 213.]
 [144. 185.]
 [316.  93.]
 [278.   4.]]
Downscale image/office

216it [00:00, 262.00it/s]

Downscale image/office activities/filing.seated/25.jpg to the height 400px
[189] /var/data/MET2/image/office activities/filing.seated/25.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [350. 410.]
 [426. 359.]
 [518. 394.]
 [397. 465.]
 [ -1.  -1.]
 [367. 214.]
 [441. 231.]
 [442. 127.]
 [528. 177.]
 [408. 325.]
 [303. 281.]
 [483. 107.]
 [427.   0.]]
Downscale image/office activities/typing/36.bmp to the height 400px
[191] /var/data/MET2/image/office activities/typing/36.bmp contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [545. 788.]
 [311. 754.]
 [412. 662.]
 [585. 743.]
 [ -1.  -1.]
 [539. 535.]
 [365. 644.]
 [269. 356.]
 [303. 274.]
 [374. 552.]
 [518. 507.]
 [376. 287.]
 [463. 138.]]
[194] /var/data/MET2/image/office activities/writing/14.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 96. 116.]
 [ 10. 113.]
 [ 56.  36.]
 [143.  76.]
 [224. 

270it [00:01, 238.81it/s]

Downscale image/office activities/walking about/57.png to the height 400px
Downscale image/resting/seated.quiet/55.jpg to the height 400px
[238] /var/data/MET2/image/office activities/reading.seated/56.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [197. 158.]
 [156. 161.]
 [149. 132.]
 [182. 127.]
 [190. 154.]
 [207. 157.]
 [170. 125.]
 [187.  99.]]
Downscale image/resting/reclining/30.jpg to the height 400px
Downscale image/office activities/walking about/45.png to the height 400px
Downscale image/office activities/reading.seated/47.png to the height 400px
Downscale image/resting/seated.quiet/36.jpg to the height 400px
[245] /var/data/MET2/image/resting/sleeping/19.png contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [279. 153.]
 [226. 105.]
 [244.  29.]
 [301. 131.]
 [ -1.  -1.]
 [ 43.  70.]
 [ 40. 119.]
 [ 88.  92.]
 [112.  21.]
 [199.  38.]
 [227.  90.]
 [ 99.  73.]
 [ 

330it [00:01, 246.22it/s]

[276] /var/data/MET2/image/office activities/typing/19.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [127. 126.]
 [144. 115.]
 [155.  69.]
 [223.  69.]
 [222. 123.]
 [176. 127.]
 [178.  70.]
 [174.  23.]]
[279] /var/data/MET2/image/office activities/writing/60.jpeg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [148.  96.]
 [115. 133.]
 [108.  78.]
 [181.  63.]
 [194. 104.]
 [200. 128.]
 [147.  64.]
 [139.   8.]]
Downscale image/office activities/reading.seated/46.jpg to the height 400px
Downscale image/office activities/walking about/48.png to the height 400px
Downscale image/office activities/typing/34.bmp to the height 400px
[283] /var/data/MET2/image/office activities/typing/34.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ 

359it [00:01, 245.82it/s]

Downscale image/office activities/typing/50.bmp to the height 400px
[333] /var/data/MET2/image/office activities/typing/50.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [372. 562.]
 [513. 554.]
 [521. 303.]
 [818. 315.]
 [796. 648.]
 [546. 602.]
 [585. 304.]
 [506. 145.]]
Downscale image/office activities/filing.seated/52.jpg to the height 400px
[338] /var/data/MET2/image/office activities/filing.seated/52.jpg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [800. 655.]
 [699. 508.]
 [896. 505.]
 [742. 568.]
 [ -1.  -1.]
 [515. 477.]
 [625. 390.]
 [670. 266.]
 [937. 294.]
 [844. 478.]
 [713. 504.]
 [808. 254.]
 [790.  85.]]
Downscale image/office activities/walking about/59.jpg to the height 400px
Downscale image/resting/reclining/32.jpg to the height 400px
Downscale image/resting/sleeping/23.jpg to the height 400px
[345] /var/data/MET2/image/office activities/writing/2.jpe

380it [00:01, 240.42it/s]
32it [00:00, 264.76it/s]

Downscale image/office activities/walking about/58.png to the height 400px
[373] /var/data/MET2/image/office activities/walking about/58.png contains non-valid joints
[1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[453. 753.]
 [443. 676.]
 [408. 454.]
 [548. 454.]
 [512. 671.]
 [ -1.  -1.]
 [365. 337.]
 [391. 361.]
 [399. 211.]
 [600. 228.]
 [583. 388.]
 [586. 501.]
 [500. 169.]
 [494.  44.]]
Downscale image/resting/reclining/31.jpg to the height 400px
[376] /var/data/MET2/image/office activities/writing/39.jpeg contains non-valid joints
[0 1 1 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 55. 160.]
 [133. 148.]
 [197. 159.]
 [180. 169.]
 [ -1.  -1.]
 [161. 128.]
 [113. 134.]
 [128.  74.]
 [206.  85.]
 [228. 142.]
 [205. 154.]
 [164.  69.]
 [161.   9.]]
Downscale image/office activities/walking about/54.jpg to the height 400px
[378] /var/data/MET2/image/office activities/walking about/54.jpg contains non-valid joints
[0 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [264. 450.]
 [302. 294.]
 [273. 317.]
 [269. 449

92it [00:00, 269.82it/s]

[0 1 0 1 1 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ 82. 155.]
 [ -1.  -1.]
 [ 94. 161.]
 [200. 179.]
 [ -1.  -1.]
 [127.  92.]
 [137. 112.]
 [148.  72.]
 [213.  78.]
 [178. 143.]
 [121. 148.]
 [176.  61.]
 [155.  14.]]
Downscale image/office activities/walking about/53.jpg to the height 400px
Downscale image/resting/sleeping/21.jpg to the height 400px
Downscale image/office activities/filing.stand/59.PNG to the height 400px
[49] /var/data/MET2/image/office activities/filing.stand/59.PNG contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [275. 238.]
 [236. 331.]
 [137. 272.]
 [152. 237.]
 [240. 219.]
 [269. 161.]
 [138. 211.]
 [143. 125.]]
[50] /var/data/MET2/image/office activities/reading.seated/9.bmp contains non-valid joints
[0 0 1 1 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ 74. 123.]
 [115. 108.]
 [ -1.  -1.]
 [ -1.  -1.]
 [101.  96.]
 [ 69.  89.]
 [ 57.  51.]
 [114.  40.]
 [115.  86.]
 [136.  77.

96it [00:00, 242.55it/s]


Downscale image/office activities/walking about/22.png to the height 400px
Downscale image/office activities/reading.seated/8.jpg to the height 400px
[94] /var/data/MET2/image/office activities/reading.seated/8.jpg contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [266. 310.]
 [137. 360.]
 [ 99. 118.]
 [281. 135.]
 [279. 348.]
 [388. 251.]
 [222. 128.]
 [265.   5.]]
[95] /var/data/MET2/image/office activities/writing/14.bmp contains non-valid joints
[0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [ -1.  -1.]
 [141. 126.]
 [164. 140.]
 [180.  82.]
 [219.  82.]
 [221. 145.]
 [154. 154.]
 [200.  64.]
 [199.  11.]]
96 images loaded
joints shape: (14, 2)
activity-met_n10_ub_train_k4.csv
380
activity-met_n10_ub_val_k4.csv
96
[Warning] During rotation, joint [ 99. 143.] becomes invalid [ 89.01667905 143.65564237].
[Warning] During rotation, joint [  4. 261.] bec